-from floodsystem.stationdata import build_station_list
-from floodsystem.geo import stations_by_river, rivers_with_station
-
-def run():
-    """Requirements for Task 1D"""
-
-    # Build list of stations
-    try:
-      stations = build_station_list()
-    except:
-      raise RuntimeError('Failed to build list of stations')
-    
-    rivers = rivers_with_station(stations)   #create set of all rivers
-    
-    print('total number of rivers is ',len(rivers))
-    rivers_list = list(rivers)
-    rivers_list.sort()
-    print('first 10 rivers are: ', rivers_list[:9])